### ISSUE TITLE
Failed to build if `updateBaseURL` is empty

### ISSUE THREAD

**Issue by vitoyucepi** [momocow/webpack-userscript#82]
## Summary

If the `updateBaseURL` option is undefined, then the build will fail.

```
@utils/webpack:     at new NodeError (node:internal/errors:399:5)
@utils/webpack:     at URL.onParseError (node:internal/url:565:9)
@utils/webpack:     at new URL (node:internal/url:645:5)
@utils/webpack:     at /tmp/test/node_modules/webpack-userscript/lib/features/resolve-base-urls.ts:36:17
@utils/webpack:     at _next0 (eval at create (/tmp/test/node_modules/tapable/lib/HookCodeFactory.js:75:10), <anonymous>:30:16)
@utils/webpack:     at eval (eval at create (/tmp/test/node_modules/tapable/lib/HookCodeFactory.js:75:10), <anonymous>:92:1)
@utils/webpack:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

## Version

Webpack: *5.75.0*
Webpack-userscript: *3.0.0*

## Additional
https://github.com/momocow/webpack-userscript/blob/aa441fd4a6e1b304c423c30d905314b0f1ed5cb3/lib/features/resolve-base-urls.ts#L35-L39

**Comment by momocow** [comment]
Thanks for reporting the issue!
