### ISSUE TITLE
The headers validate feature is missing some valid values.

### ISSUE THREAD

**Issue by yingziwu** [momocow/webpack-userscript#87]
The headers validate feature is missing some valid values and cause build failed!

Project: https://github.com/404-novel-project/novel-downloader/tree/webpack-userscript

```
$ yarn build
development: false
commit count: 821
version: 5.1.821
[webpack-cli] HookWebpackError: An instance of Headers has failed the validation:
 - property name:en has failed the following constraints: whitelistValidation 

An instance of Headers has failed the validation:
 - property name:ja has failed the following constraints: whitelistValidation 

An instance of Headers has failed the validation:
 - property description:en has failed the following constraints: whitelistValidation 

An instance of Headers has failed the validation:
 - property description:ja has failed the following constraints: whitelistValidation 

An instance of Headers has failed the validation:
 - property license has failed the following constraints: whitelistValidation 

An instance of Headers has failed the validation:
 - property compatible has failed the following constraints: whitelistValidation 

An instance of Headers has failed the validation:
 - property incompatible has failed the following constraints: whitelistValidation 

    at makeWebpackError (/srv/app/404-novel-project/novel-downloader/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /srv/app/404-novel-project/novel-downloader/node_modules/webpack/lib/Compilation.js:3060:12
    at eval (eval at create (/srv/app/404-novel-project/novel-downloader/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:34:1)
-- inner error --
Error: An instance of Headers has failed the validation:
 - property name:en has failed the following constraints: whitelistValidation 

An instance of Headers has failed the validation:
 - property name:ja has failed the following constraints: whitelistValidation 

An instance of Headers has failed the validation:
 - property description:en has failed the following constraints: whitelistValidation 

An instance of Headers has failed the validation:
 - property description:ja has failed the following constraints: whitelistValidation 

An instance of Headers has failed the validation:
 - property license has failed the following constraints: whitelistValidation 

An instance of Headers has failed the validation:
 - property compatible has failed the following constraints: whitelistValidation 

An instance of Headers has failed the validation:
 - property incompatible has failed the following constraints: whitelistValidation 

    at ValidateHeaders.validateHeaders (/srv/app/404-novel-project/novel-downloader/node_modules/webpack-userscript/dist/features/validate-headers/impl.js:33:23)
    at /srv/app/404-novel-project/novel-downloader/node_modules/webpack-userscript/dist/features/validate-headers/impl.js:16:61
    at _next3 (eval at create (/srv/app/404-novel-project/novel-downloader/node_modules/webpack-userscript/node_modules/tapable/lib/HookCodeFactory.js:75:10), <anonymous>:42:16)
    at eval (eval at create (/srv/app/404-novel-project/novel-downloader/node_modules/webpack-userscript/node_modules/tapable/lib/HookCodeFactory.js:75:10), <anonymous>:91:1)
caused by plugins in Compilation.hooks.processAssets
Error: An instance of Headers has failed the validation:
 - property name:en has failed the following constraints: whitelistValidation 

An instance of Headers has failed the validation:
 - property name:ja has failed the following constraints: whitelistValidation 

An instance of Headers has failed the validation:
 - property description:en has failed the following constraints: whitelistValidation 

An instance of Headers has failed the validation:
 - property description:ja has failed the following constraints: whitelistValidation 

An instance of Headers has failed the validation:
 - property license has failed the following constraints: whitelistValidation 

An instance of Headers has failed the validation:
 - property compatible has failed the following constraints: whitelistValidation 

An instance of Headers has failed the validation:
 - property incompatible has failed the following constraints: whitelistValidation 

    at ValidateHeaders.validateHeaders (/srv/app/404-novel-project/novel-downloader/node_modules/webpack-userscript/dist/features/validate-headers/impl.js:33:23)
    at /srv/app/404-novel-project/novel-downloader/node_modules/webpack-userscript/dist/features/validate-headers/impl.js:16:61
    at _next3 (eval at create (/srv/app/404-novel-project/novel-downloader/node_modules/webpack-userscript/node_modules/tapable/lib/HookCodeFactory.js:75:10), <anonymous>:42:16)
    at eval (eval at create (/srv/app/404-novel-project/novel-downloader/node_modules/webpack-userscript/node_modules/tapable/lib/HookCodeFactory.js:75:10), <anonymous>:91:1)  
```

Version
--------------------------------------

webpack: 5.76.1
webpack-userscript: 3.1.0

Additional
--------------------------------------------------

https://github.com/momocow/webpack-userscript/blob/3bc5d5cf85f6208a09b31ec01966c9199c328d2f/lib/features/validate-headers/headers.ts#L22-L171

Some references:
- [Metadata Block - GreaseSpot Wiki](https://wiki.greasespot.net/Metadata_Block)
- [Documentation | Tampermonkey](https://www.tampermonkey.net/documentation.php)
- [Metadata Block | Violentmonkey](https://violentmonkey.github.io/api/metadata-block/)
- [Script meta keys read by Greasy Fork](https://greasyfork.org/en/help/meta-keys)

Some missing values:
- ``@copyright`` by [Tampermonkey](https://www.tampermonkey.net/documentation.php#meta:copyright)
- ``@sandbox`` by [Tampermonkey](https://www.tampermonkey.net/documentation.php#meta:sandbox)
- ``@exclude-match`` by [Violentmonkey](https://violentmonkey.github.io/api/metadata-block/#match--exclude-match)
- ``@inject-into`` by [Violentmonkey](https://violentmonkey.github.io/api/metadata-block/#inject-into)
- ``@name:XX-YY`` by [Greasy Fork](https://greasyfork.org/en/help/meta-keys#meta-name-localized)
- ``@description:XX-YY`` by [Greasy Fork](https://greasyfork.org/en/help/meta-keys#meta-name-description)
- ``@license`` by [Greasy Fork](https://greasyfork.org/en/help/meta-keys#meta-license)
- ``@contributionURL`` by [Greasy Fork](https://greasyfork.org/en/help/meta-keys#meta-contributionURL)
- ``@contributionAmount`` by [Greasy Fork](https://greasyfork.org/en/help/meta-keys#meta-contributionAmount)
- ``@compatible`` by [Greasy Fork](https://greasyfork.org/en/help/meta-keys#meta-compatible)
- ``@incompatible`` by [Greasy Fork](https://greasyfork.org/en/help/meta-keys#meta-incompatible)
- ``@antifeature:XX-YY`` by [Greasy Fork](https://greasyfork.org/en/help/meta-keys#meta-antifeature-localized)

**Comment by momocow** [comment]
Wow, such a nice list of missing values! Thank you!

**Comment by ilyhalight** [comment]
> Wow, such a nice list of missing values! Thank you!

Any news on the release date of the update with these changes?

**Comment by momocow** [comment]
@ilyhalight 3 days maybe.

Some tags have already been added in the `dev` branch; however, I'm currently dealing with the localization tags like `@name:XX-YY` introduced by Greasy Fork.
